[jim]
version = "5.0.0"
token = "" # put your discord token here
default_prefix = "-dev" # all guilds will use this prefix unless changed
shard_count = 1 # amount of shards jim will create

[database]
user = "" # put your postgres username here
pass = "" # put your postgres password here
jdbc_url = "jdbc:postgresql://(host_name):(port)/(database_name)"

[botlist]
enabled = false # be careful with enabling this, bot will fail every time it tries to update lists if you have missing tokens

[[botlist.list]]
name = "Discord Bot List"
url = "https://discordbots.org/api/bots/$id/stats"
token = ""
ignore_errors = false

[oauth]
client_id = "" # your client_id given by discord
client_secret = "" # your client_secret given by discord
redirect_uri = "" # uri you set in developer panel

[server]
secret = "" # secret to be used with JWT
base_url = "http://safetyjim.xyz"
port = 8080